spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.1.13/sell?characterEncoding=utf8&useSSL=false

  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null

  redis:
    host: 192.168.1.13
    port: 6379
server:
  servlet:
    context-path: /sell

wechat:
  mpAppId: a
  mpAppSecret: a
  openAppId: a
  openAppSecret: a
  mchId: a
  mchKey: a
  keyPath: a
  notifyUrl: a
  templateId:
    orderStatus: a

projectconfigurl:
  wechatMpAuthrize: a
  wechatOpenAuthorize: a
  sell: a
logging:
  level:
    com.chen.sell.dataobject.mapper: trace
mybatis:
  mapper-locations: classpath:mapper/*.xml



