spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.1.8/sell?characterEncoding=utf8&useSSL=false
  jpa:
    show-sql: true


